"""The A2A agent card's skills (generated by genproj).

The card is owned by the container: it is declared here and re-registered with
the LiteLLM gateway on startup, so a changed skill or description ships with the
image instead of drifting in a UI. Describe the domain honestly - LiteLLM's
agent registry matches a task against the card's name, description and skills by
semantic similarity, so a placeholder description is how a router fails to find
the agent.

The name, description and protocol version come from agent/main.py and the
capability configuration; this file owns only the skills.
"""

from __future__ import annotations

from fasta2a import Skill

AGENT_SKILLS: list[Skill] = [
    Skill(
        id="answer",
        name="data-sourcing-agent",
        description="Turns a fuzzy market-data need into a validated, costed Databento download ticket (requests/*.yaml) for human sign-off. Drafts only: it cannot spend credit, cannot approve a request, and is not the authority on whether a request is legal - the validator tool is. Covers Databento historical US equities, futures and options datasets.",
        tags=["data-sourcing-agent", "a2a"],
        input_modes=["application/json"],
        output_modes=["application/json"],
        examples=["Ask data-sourcing-agent a question in its domain."],
    ),
]
