"""The A2A agent card's skills (generated by genproj, retargeted to a2a-sdk).

The card is owned by the container: it is declared here and re-registered with
the LiteLLM gateway on startup, so a changed skill or description ships with the
image instead of drifting in a UI. Describe the domain honestly - LiteLLM's
agent registry matches a task against the card's name, description and skills by
semantic similarity, so a placeholder description is how a router fails to find
the agent.

The skills are plain dictionaries so the same source feeds both consumers:

  * the **served** card (`GET /.well-known/agent-card.json`), built as an
    a2a-sdk `AgentCard` proto by `build_agent_card`; and
  * the **registration** payload POSTed to LiteLLM's `/v1/agents`, which
    `agent/register.py` serialises straight to JSON.

Doing it this way (rather than with `fasta2a.Skill`) is what lets the whole
`fasta2a` dependency go.
"""

from __future__ import annotations

from a2a.types.a2a_pb2 import AgentCapabilities, AgentCard, AgentInterface, AgentSkill

AGENT_SKILLS: list[dict] = [
    {
        "id": "answer",
        "name": "data-sourcing-agent",
        "description": "Turns a fuzzy market-data need into a validated, costed Databento download ticket (requests/*.yaml) for human sign-off. Drafts only: it cannot spend credit, cannot approve a request, and is not the authority on whether a request is legal - a deterministic validator asks the Databento API. Covers Databento historical US equities, futures and options datasets.",
        "tags": ["data-sourcing-agent", "a2a"],
        "inputModes": ["application/json"],
        "outputModes": ["application/json"],
        "examples": ["Ask data-sourcing-agent a question in its domain."],
    },
]


def build_agent_card(
    *,
    name: str,
    description: str,
    url: str,
    protocol_version: str,
    version: str = "0.1.0",
    skills: list[dict] | None = None,
) -> AgentCard:
    """Build the served `AgentCard` for the a2a-sdk server.

    `url` is the address a caller DIALS (the LiteLLM proxy, from its vantage on
    `ai_proxy`), and `protocol_version` is the wire the JSON-RPC endpoint
    actually speaks - both come from `agent/main.py`, so the served card cannot
    drift from the server it describes. See the handover memo §4 for why the
    dial address and the wire version are load-bearing.
    """
    return AgentCard(
        name=name,
        description=description,
        version=version,
        supported_interfaces=[
            AgentInterface(
                url=url,
                protocol_binding="JSONRPC",
                protocol_version=protocol_version,
            )
        ],
        capabilities=AgentCapabilities(streaming=False),
        default_input_modes=["application/json", "text/plain"],
        default_output_modes=["application/json", "text/plain"],
        skills=[
            AgentSkill(
                id=skill["id"],
                name=skill["name"],
                description=skill["description"],
                tags=skill.get("tags", []),
                examples=skill.get("examples", []),
            )
            for skill in (skills if skills is not None else AGENT_SKILLS)
        ],
    )
