"""A2A server for the "data-sourcing-agent" agent (generated by genproj).

Run it with:

    uvicorn agent.main:app --host 0.0.0.0 --port 8700

The A2A app, agent card and JSON-RPC transport come from the **official
a2a-sdk** (`a2a.server`); this module wires a Pydantic AI agent into it. Startup
self-registration with the LiteLLM gateway lives in agent/register.py.

Why a2a-sdk and not FastA2A: the LiteLLM gateway invokes this agent with an
a2a-sdk 1.1.0 client, and FastA2A 2.0.1 could not be spoken to by it - its card
declared a "1.0" interface while the server only spoke the 0.3 wire, and its
`result.task` envelope was unparseable by the client. Using the same SDK on both
sides of the wire removes the skew by construction. `a2a-sdk` is pinned to the
gateway's client version (pyproject).

Bind 0.0.0.0, not 127.0.0.1: the caller is the LiteLLM proxy reaching this
container across the network, so a loopback bind is unreachable.
"""

from __future__ import annotations

import json
import os
from contextlib import asynccontextmanager
from pathlib import Path

from a2a.helpers.proto_helpers import new_task_from_user_message, new_text_part
from a2a.server.agent_execution import AgentExecutor, RequestContext
from a2a.server.events.event_queue import EventQueue
from a2a.server.request_handlers import DefaultRequestHandler
from a2a.server.routes import create_agent_card_routes, create_jsonrpc_routes
from a2a.server.tasks import InMemoryTaskStore
from a2a.server.tasks.task_updater import TaskUpdater
from pydantic_ai import Agent, ModelSettings, PromptedOutput
from pydantic_ai.mcp import MCPToolset
from starlette.applications import Starlette
from starlette.middleware import Middleware
from starlette.requests import Request
from starlette.responses import JSONResponse
from starlette.routing import Route

from agent.card import AGENT_SKILLS, build_agent_card
from agent.contract import validate_agent_result
from agent.headers import capture_litellm_headers
from agent.model import build_model
from agent.register import register_with_litellm
from agent.ticket import TicketProposal, render_ticket_yaml

PACKAGE_ROOT = Path(__file__).resolve().parent
INSTRUCTIONS_PATH = PACKAGE_ROOT.parent / "prompts" / "instructions.md"

AGENT_NAME = "data-sourcing-agent"
AGENT_DESCRIPTION = "Turns a fuzzy market-data need into a validated, costed Databento download ticket (requests/*.yaml) for human sign-off. Drafts only: it cannot spend credit, cannot approve a request, and is not the authority on whether a request is legal - a deterministic validator asks the Databento API. Covers Databento historical US equities, futures and options datasets."
# The wire the a2a-sdk JSON-RPC endpoint speaks. The SDK's native server is the
# "1.0" wire (`SendMessage`), and the same value is registered with LiteLLM. The
# endpoint also enables the SDK's v0.3 compatibility layer (see create_app), so
# a legacy `message/send` caller still works - but the card advertises 1.0, which
# is what the SDK server natively speaks.
PROTOCOL_VERSION = "1.0"
# The URL the card advertises — the address the LiteLLM proxy DIALS, from its
# own vantage on `ai_proxy`. `0.0.0.0` is a *bind* address: the proxy reading it
# would dial itself, so registration would succeed and invocation would fail.
# The container's own name on `ai_proxy` is what the proxy's embedded DNS
# resolves, so that is the default. See the handover memo §4.
CARD_URL = os.environ.get("A2A_CARD_URL", "http://data-sourcing-agent:8700")


def _load_instructions() -> str:
    """The agent's instructions, read fresh from prompts/instructions.md.

    That file is human-owned: genproj seeds it once and regeneration never
    overwrites it, so instruction changes do not require regeneration.
    """
    if INSTRUCTIONS_PATH.exists():
        return INSTRUCTIONS_PATH.read_text(encoding="utf-8")
    return "You are the front desk for Databento historical downloads. Turn a human's intent into a draft download ticket. You never mark a ticket approved, never raise cost.max_usd, and never declare a request valid or a cost known - the deterministic Validator asks the Databento API, and only a human signs off on spend. `stype_in` is one of raw_symbol, parent, continuous, instrument_id, and you must not guess it. `why` is mandatory."


AGENT_TOOLSETS = [
    MCPToolset("http://mcphub:3000/mcp/databento-discovery"),
]

agent = Agent(
    build_model(),
    instructions=_load_instructions(),
    # `PromptedOutput`, NOT the default `ToolOutput`: `deepseek-v4-flash` is a
    # thinking model and refuses a forced `tool_choice` ("Thinking mode does not
    # support this tool_choice"), and the gateway's provider rejects a
    # `json_schema` response_format ("This response_format type is unavailable
    # now"). PromptedOutput asks for JSON in the prompt and parses it — verified
    # to round-trip on this alias (handover memo §5.1). `NativeOutput` fails; do
    # not "upgrade" to it without re-testing.
    output_type=PromptedOutput(TicketProposal),
    # Reasoning tokens bill against `max_tokens` on this model, so a low cap
    # truncates the answer before it is emitted. The default is too small.
    model_settings=ModelSettings(max_tokens=4096),
    retries={"output": 3},
    toolsets=AGENT_TOOLSETS,
)
# The Validator layer. It runs on every model output; on failure it raises
# ModelRetry with real error text, up to `retries["output"]` times.
agent.output_validator(validate_agent_result)


async def healthz(_: Request) -> JSONResponse:
    """Liveness for the container healthcheck and the Homepage widget."""
    return JSONResponse({"status": "ok"})


async def _register() -> None:
    """Register this agent's card with the LiteLLM gateway, once, at startup."""
    await register_with_litellm(
        agent_name=AGENT_NAME,
        card_url=CARD_URL,
        protocol_version=PROTOCOL_VERSION,
        description=AGENT_DESCRIPTION,
        skills=AGENT_SKILLS,
    )


class TicketAgentExecutor(AgentExecutor):
    """Runs the Pydantic AI agent for one A2A request and returns its ticket.

    The SDK calls `execute` with the request's `RequestContext` (which carries
    the user message and the `ServerCallContext`) and an `EventQueue` to publish
    events on. We publish a working status, run the agent, publish the rendered
    ticket as an artifact, and complete.

    The request headers reach `current_litellm_headers()` here: the SDK's
    default context builder records them in `call_context.state['headers']`, and
    `capture_litellm_headers` puts them in the context variable that
    `HeaderForwardingClient` injects on the agent's own model calls.
    """

    def __init__(self, agent: Agent):
        self._agent = agent

    async def execute(self, context: RequestContext, event_queue: EventQueue) -> None:
        # The a2a-sdk event pipeline requires the Task to be enqueued before any
        # status/artifact update (otherwise the consumer raises
        # InvalidAgentResponseError). On a fresh request we mint it from the user
        # message; on a follow-up the framework hands us the stored task.
        initial_task = context.current_task
        if initial_task is None and context.message is not None:
            initial_task = new_task_from_user_message(context.message)
        if initial_task is not None:
            await event_queue.enqueue_event(initial_task)

        updater = TaskUpdater(event_queue, context.task_id, context.context_id)
        await updater.start_work()
        capture_litellm_headers(context.call_context.state.get("headers"))
        try:
            result = await self._agent.run(context.get_user_input())
            ticket = result.output
            rendered = render_ticket_yaml(ticket)
        except Exception as exc:  # a failed turn is a failed task, not a crash
            await updater.failed(
                updater.new_agent_message([new_text_part(f"The run failed: {exc}")])
            )
            return
        await updater.add_artifact([new_text_part(rendered)], name="ticket")
        await updater.complete()

    async def cancel(self, context: RequestContext, event_queue: EventQueue) -> None:
        updater = TaskUpdater(event_queue, context.task_id, context.context_id)
        await updater.cancel()


class A2AVersionHeaderMiddleware:
    """Supply the `A2A-Version` header the SDK dispatcher validates.

    The SDK's dispatcher rejects a request whose `A2A-Version` header disagrees
    with the dialect it routed to, and treats a *missing* header as "0.3". The
    a2a-sdk client sets the header, but a client that omits it (or a raw probe)
    would be rejected on the 1.0 path. So when the header is absent we supply
    the version that matches the JSON-RPC method: the v0.3 methods are the ones
    with a `/` in them (`message/send`), everything else is 1.0 (`SendMessage`).
    An explicit header is never overridden.
    """

    def __init__(self, app):
        self.app = app

    async def __call__(self, scope, receive, send):
        if scope.get("type") != "http":
            await self.app(scope, receive, send)
            return
        if any(key.lower() == b"a2a-version" for key, _ in scope.get("headers", [])):
            await self.app(scope, receive, send)
            return

        body = b""
        more = True
        while more:
            message = await receive()
            body += message.get("body", b"")
            more = message.get("more_body", False)
        try:
            method = json.loads(body or b"{}").get("method", "")
        except (TypeError, ValueError):
            method = ""
        version = "0.3" if "/" in method else PROTOCOL_VERSION
        scope = dict(scope)
        scope["headers"] = [*scope.get("headers", []), (b"a2a-version", version.encode())]

        async def replay():
            return {"type": "http.request", "body": body, "more_body": False}

        await self.app(scope, replay, send)


def create_app(*, agent_executor: AgentExecutor | None = None, agent_instance: Agent | None = None) -> Starlette:
    """Build the ASGI app. `agent_instance`/`agent_executor` are injection points for tests."""
    card = build_agent_card(
        name=AGENT_NAME,
        description=AGENT_DESCRIPTION,
        url=CARD_URL,
        protocol_version=PROTOCOL_VERSION,
        skills=AGENT_SKILLS,
    )
    executor = agent_executor or TicketAgentExecutor(agent)
    request_handler = DefaultRequestHandler(
        agent_executor=executor,
        task_store=InMemoryTaskStore(),
        agent_card=card,
    )
    inner_agent = agent_instance if agent_instance is not None else agent

    @asynccontextmanager
    async def lifespan(_app: Starlette):
        async with inner_agent:
            await _register()
            yield

    return Starlette(
        routes=[
            *create_agent_card_routes(card),
            # v0.3 compatibility keeps the legacy `message/send` dialect working
            # on the same endpoint, so a caller that reads the card as 0.3 is not
            # locked out. The native 1.0 path is what the card advertises.
            *create_jsonrpc_routes(request_handler, rpc_url="/", enable_v0_3_compat=True),
            Route("/healthz", healthz),
        ],
        middleware=[Middleware(A2AVersionHeaderMiddleware)],
        lifespan=lifespan,
    )


app = create_app()
