"""A2A server for the "data-sourcing-agent" agent (generated by genproj).

Run it with:

    uvicorn agent.main:app --host 0.0.0.0 --port 8700

The A2A app, agent card and JSON-RPC transport come from FastA2A; this module
wires a Pydantic AI agent into it. Startup self-registration with the LiteLLM
gateway lives in agent/register.py.

Bind 0.0.0.0, not 127.0.0.1: the caller is the LiteLLM proxy reaching this
container across the network, so a loopback bind is unreachable.
"""

from __future__ import annotations

import os
from contextlib import asynccontextmanager
from pathlib import Path

from fasta2a import FastA2A
from fasta2a.broker import InMemoryBroker
from fasta2a.pydantic_ai import worker_lifespan
from fasta2a.storage import InMemoryStorage
from pydantic_ai import Agent, ModelSettings, PromptedOutput
from pydantic_ai.mcp import MCPToolset
from starlette.middleware import Middleware
from starlette.requests import Request
from starlette.responses import JSONResponse
from starlette.routing import Route

from agent.card import AGENT_SKILLS
from agent.contract import validate_agent_result
from agent.headers import HeaderForwardingWorker, LiteLLMHeaderMiddleware
from agent.model import build_model
from agent.register import register_with_litellm
from agent.ticket import TicketProposal

PACKAGE_ROOT = Path(__file__).resolve().parent
INSTRUCTIONS_PATH = PACKAGE_ROOT.parent / "prompts" / "instructions.md"

AGENT_NAME = "data-sourcing-agent"
AGENT_DESCRIPTION = "Turns a fuzzy market-data need into a validated, costed Databento download ticket (requests/*.yaml) for human sign-off. Drafts only: it cannot spend credit, cannot approve a request, and is not the authority on whether a request is legal - a deterministic validator asks the Databento API. Covers Databento historical US equities, futures and options datasets."
PROTOCOL_VERSION = "1.0"
# The URL the card advertises — the address the LiteLLM proxy DIALS, from its
# own vantage on `ai_proxy`. `0.0.0.0` is a *bind* address: the proxy reading it
# would dial itself, so registration would succeed and invocation would fail.
# The container's own name on `ai_proxy` is what the proxy's embedded DNS
# resolves, so that is the default. See the handover memo §4.
CARD_URL = os.environ.get("A2A_CARD_URL", "http://data-sourcing-agent:8700")


def _load_instructions() -> str:
    """The agent's instructions, read fresh from prompts/instructions.md.

    That file is human-owned: genproj seeds it once and regeneration never
    overwrites it, so instruction changes do not require regeneration.
    """
    if INSTRUCTIONS_PATH.exists():
        return INSTRUCTIONS_PATH.read_text(encoding="utf-8")
    return "You are the front desk for Databento historical downloads. Turn a human's intent into a draft download ticket. You never mark a ticket approved, never raise cost.max_usd, and never declare a request valid or a cost known - the deterministic Validator asks the Databento API, and only a human signs off on spend. `stype_in` is one of raw_symbol, parent, continuous, instrument_id, and you must not guess it. `why` is mandatory."


AGENT_TOOLSETS = [
    MCPToolset("http://mcphub:3000/mcp/databento-discovery"),
]

agent = Agent(
    build_model(),
    instructions=_load_instructions(),
    # `PromptedOutput`, NOT the default `ToolOutput`: `deepseek-v4-flash` is a
    # thinking model and refuses a forced `tool_choice` ("Thinking mode does not
    # support this tool_choice"), and the gateway's provider rejects a
    # `json_schema` response_format ("This response_format type is unavailable
    # now"). PromptedOutput asks for JSON in the prompt and parses it — verified
    # to round-trip on this alias (handover memo §5.1). `NativeOutput` fails; do
    # not "upgrade" to it without re-testing.
    output_type=PromptedOutput(TicketProposal),
    # Reasoning tokens bill against `max_tokens` on this model, so a low cap
    # truncates the answer before it is emitted. The default is too small.
    model_settings=ModelSettings(max_tokens=4096),
    retries={"output": 3},
    toolsets=AGENT_TOOLSETS,
)
# The Validator layer. It runs on every model output; on failure it raises
# ModelRetry with real error text, up to `retries["output"]` times.
agent.output_validator(validate_agent_result)

# The worker is built at import time so the lifespan can hand the SAME instance
# to FastA2A and to worker_lifespan. HeaderForwardingWorker is the Pydantic AI
# worker with the LiteLLM context headers put back in scope for the task (see
# agent/headers.py) - the plain AgentWorker would lose them.
storage = InMemoryStorage()
broker = InMemoryBroker()
worker = HeaderForwardingWorker(agent=agent, broker=broker, storage=storage)


async def healthz(_: Request) -> JSONResponse:
    """Liveness for the container healthcheck and the Homepage widget."""
    return JSONResponse({"status": "ok"})


async def _register() -> None:
    """Register this agent's card with the LiteLLM gateway, once, at startup."""
    await register_with_litellm(
        agent_name=AGENT_NAME,
        card_url=CARD_URL,
        protocol_version=PROTOCOL_VERSION,
        description=AGENT_DESCRIPTION,
        skills=AGENT_SKILLS,
    )


@asynccontextmanager
async def _lifespan(app: FastA2A):
    """Run the worker for the app's lifetime, and register once it is up."""
    async with worker_lifespan(app, worker=worker, agent=agent):
        await _register()
        yield


def create_app() -> FastA2A:
    return FastA2A(
        storage=storage,
        broker=broker,
        name=AGENT_NAME,
        url=CARD_URL,
        description=AGENT_DESCRIPTION,
        skills=AGENT_SKILLS,
        routes=[Route("/healthz", healthz)],
        middleware=[Middleware(LiteLLMHeaderMiddleware)],
        lifespan=_lifespan,
    )


app = create_app()
